Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

Feature:
 - head-branch: ['add:*']

Fix:
 - head-branch: ['fix:*']

Next-Release:
 - head-branch: ['chore: release*', 'release-please*']

Command:
- changed-files:
  - any-glob-to-any-file: 'src/Console/Command/**'

Frontend:
- changed-files:
  - any-glob-to-any-file: 'src/view/frontend/**'

Theme-Builder:
- changed-files:
  - any-glob-to-any-file: 'src/Service/ThemeBuilder/**'
