# Add 'Documentation' label to any change to .md files within the entire repository 
Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

feature:
 - head-branch: ['^add','feature','add:']

fix:
 - head-branch: ['^fix','fix','fix:']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'
