Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

Feature:
 - branch: ['add-*', 'featuere-*', 'feature/**', 'feat-*', 'feature*']
 - title: ['feat:', 'feature:', 'Feature:']

Fix:
 - branch: ['fix-*', 'bugfix-*', 'fix/**', 'bugfix/**', 'fix*', 'bugfix*']
 - title: ['fix:', 'bugfix:', 'Fix:']

Next-Release:
 - branch: ['chore: release*', 'release-please*']
 - title: ['chore: release', 'Release']

Command:
- changed-files:
  - any-glob-to-any-file: 'src/Console/Command/**'

Frontend:
- changed-files:
  - any-glob-to-any-file: 'src/view/frontend/**'

Theme-Builder:
- changed-files:
  - any-glob-to-any-file: 'src/Service/ThemeBuilder/**'
