# Add 'Documentation' label to any change to .md files within the entire repository 
Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

Feature:
 - head-branch: ['^add:']

Fix:
 - head-branch: ['^fix']

Next-Release:
 - head-branch: ['^chore: release']
