Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

Feature:
 - head-branch: ['^add:']

Fix:
 - head-branch: ['^fix:']

Next-Release:
 - head-branch: ['^chore: release']

Command:
- changed-files:
  - any-glob-to-any-file: 'src/Console/Command/*'

Frontend:
- changed-files:
  - any-glob-to-any-file: 'src/view/frontend/*'

ThemeBuilder:
- changed-files:
  - any-glob-to-any-file: 'src/src/Service/ThemeBuilder/*'
